# Generated by Django 4.0 on 2021-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_registerproduct_productregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WAITING', 'Waiting')], default='WAITING', max_length=10),
        ),
    ]
