# Generated by Django 4.0 on 2021-12-11 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_productregistration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='auction_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='auction_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
