# Generated by Django 4.0 on 2021-12-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionwallet',
            old_name='name',
            new_name='user',
        ),
    ]
