# Generated by Django 4.0 on 2021-12-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wallet', '0002_rename_name_auctionwallet_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionWallet',
            new_name='UserWallet',
        ),
    ]
