# Generated by Django 4.0 on 2021-12-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_mount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('TOPBIDDER', 'Top bidder'), ('CONTENDER', 'Contender')], default='CONTENDER', max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
