# Generated by Django 4.0 on 2021-12-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidlist',
            old_name='bid_mount',
            new_name='bid_amount',
        ),
    ]
