# Generated by Django 4.0 on 2021-12-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '0002_rename_bid_mount_bidlist_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidlist',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
